spring:
  application:
    name: lambda-api-call

  datasource:
    url: jdbc:mysql://localhost:3306/campus
    username: campus
    password: campus
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

schedule:
  cron: "* * 0/12 * * *"
  use: true

aws:
  region: ap-northeast-2
  lambda:
    function-name: gocamping-api-call

gocamping:
  api:
    base-url: http://apis.data.go.kr/B551011/GoCamping
    key: Au%2FsJXmqYwNOJf1Wq3qbzEo6OzW4p5KALPI2%2FnvXgdZWHiHm5jTl2dMdr%2FR75gxHwTuOeH7pVCOUkUfg4c%2FkZQ%3D%3D